// Run: node .workbuddy/check-canvas.cjs. Uses isolated memory; never reads user storage.
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const html = fs.readFileSync(path.join(__dirname,'..','idea-ops','assets','index.html'),'utf8');
const elements = new Map(), storage = new Map();
const element = key => {
  if (!elements.has(key)) elements.set(key, {innerHTML:'',hidden:true,style:{},dataset:{},offsetWidth:304,offsetHeight:220,
    handlers:{},addEventListener(name,handler){(this.handlers[name] ||= []).push(handler)},querySelectorAll(){return []},querySelector(){return null},focus(){},setAttribute(){},
    getBoundingClientRect(){return {left:0,top:0,width:800,height:700}}});
  return elements.get(key);
};
const context = vm.createContext({assert,console,Intl,Date,Map,Set,setTimeout,clearTimeout,
  FormData:class {constructor(form){return Object.entries(form.values)}},
  location:{protocol:'file:'},document:{querySelector:element},addEventListener(){},
  localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)}});
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/refresh\(\)\.then\(render\)\.catch[\s\S]*$/,'');
new vm.Script(script).runInContext(context);
vm.runInContext(`
const create = (path,payload) => localMutate(path,{body:JSON.stringify(payload)});
const project = create('/api/capture',{title:'测试项目'});
const base = '/api/ideas/'+project.id;
const add = (text,after=[]) => create(base+'/log',{kind:'step',text,after}).logs.at(-1).id;
const start=add('开始'), a=add('方案 A',[start]), b=add('方案 B',[start]);
const join=add('汇合',[a,b]);
let saved=loadLocal().ideas[0];
assert.deepEqual(saved.logs.at(-1).after,[a,b]);
assert.throws(()=>create(base+'/log-link',{source:join,target:start}),/循环/);
assert.throws(()=>add('错误父节点',['missing']),/父提交不存在/);
assert.equal(loadLocal().ideas[0].logs.length,4);
state.ideas=[saved];state.selected=saved.id;renderDetail();
assert.ok(document.querySelector('#detail').innerHTML.includes('map-scroll'));
assert.ok(!document.querySelector('#detail').innerHTML.includes('<input'));
assert.ok(!document.querySelector('#detail').innerHTML.includes('<textarea'));
selectNode(a);
assert.equal(document.querySelector('#node-tools').hidden,false);
assert.ok(document.querySelector('#node-tools').innerHTML.includes('节点详情'));
assert.ok(document.querySelector('#node-tools').innerHTML.includes('方案 A'));
assert.ok(document.querySelector('#detail').innerHTML.includes('class="node-actions"'));
assert.ok(document.querySelector('#detail').innerHTML.includes('class="edge-actions"'));
assert.ok(document.querySelector('#detail').innerHTML.includes('data-action="insert"'));
assert.ok(document.querySelector('#detail').innerHTML.includes('data-action="unlink"'));
openEditor('insert');
assert.ok(document.querySelector('#node-tools').innerHTML.includes('data-mode="insert"'));
assert.ok(document.querySelector('#node-tools').innerHTML.includes('<textarea'));
openMetadata();assert.ok(document.querySelector('#node-tools').innerHTML.includes('下一步'));
const nested=[{id:'r',parents:[]},{id:'a',parents:['r']},{id:'b',parents:['r']},
{id:'a1',parents:['a']},{id:'a2',parents:['a']},{id:'b1',parents:['b']},{id:'b2',parents:['b']},
{id:'j',parents:['a1','a2','b1','b2']}].map((n,i)=>({...n,at:String(i),text:n.id,kind:'step'}));
const layout=timelineLayout(nested);
for(const item of nested){
 const point=layout.pos.get(item.id); assert.ok(Number.isFinite(point.x)&&Number.isFinite(point.y));
 for(const parent of item.parents) assert.ok(layout.pos.get(parent).x<point.x);
 for(const other of nested) if(other.id!==item.id && layout.depth.get(other.id)===layout.depth.get(item.id))
   assert.ok(Math.abs(layout.pos.get(other.id).y-point.y)>=140);
}
create(base+'/log-delete',{log:a});
saved=loadLocal().ideas[0];assert.equal(saved.logs.length,3);
assert.deepEqual(saved.logs.find(l=>l.id===join).after,[b]);
create(base+'/log-insert',{source:b,target:join,kind:'step',text:'插入节点'});
saved=loadLocal().ideas[0];const inserted=saved.logs.at(-1).id;
assert.deepEqual(saved.logs.find(l=>l.id===join).after,[inserted]);
assert.deepEqual(saved.logs.at(-1).after,[b]);
assert.deepEqual(saved.logs.find(l=>l.id===b).after,[start]);
const beforeFailure=JSON.stringify(saved);
assert.throws(()=>create(base+'/log-insert',{source:b,target:join,kind:'step',text:'重复插入'}),/连线不存在/);
assert.equal(JSON.stringify(loadLocal().ideas[0]),beforeFailure);
create(base+'/log-unlink',{source:inserted,target:join});
saved=loadLocal().ideas[0];
assert.equal(saved.logs.length,4);
assert.deepEqual(graphNodes(saved).find(l=>l.id===join).parents,[]);
assert.ok(!graphNodes(saved).some(l=>l.id==='root'));
const beforeDelete=saved.logs.map(log=>({...log,after:[...log.after]}));
create(base+'/log-delete',{log:b});saved=loadLocal().ideas[0];
assert.deepEqual(saved.logs,beforeDelete.filter(log=>log.id!==b).map(log=>({...log,after:log.after.filter(parent=>parent!==b)})));
assert.deepEqual(graphNodes(saved).find(l=>l.id===inserted).parents,[]);
const initialPositions=initializePositions(saved);
create(base+'/log-positions',{positions:initialPositions});
saved=loadLocal().ideas[0];
assert.deepEqual(initializePositions(saved),{});
create(base+'/log-positions',{positions:{[inserted]:{x:-25000.5,y:42000.25}}});
saved=loadLocal().ideas[0];
assert.deepEqual(saved.logs.find(l=>l.id===inserted).position,{x:-25000.5,y:42000.25});
const fixed=new Map(saved.logs.map(l=>[l.id,{...l.position}]));
create(base+'/log-delete',{log:start});saved=loadLocal().ideas[0];
fixed.delete(start);
assert.deepEqual(initializePositions(saved),{});
saved.logs.forEach(l=>assert.deepEqual(l.position,fixed.get(l.id)));
const newcomer=add('新后续',[inserted]);saved=loadLocal().ideas[0];
const newPositions=initializePositions(saved);assert.deepEqual(Object.keys(newPositions),[newcomer]);
create(base+'/log-positions',{positions:newPositions});
saved=loadLocal().ideas[0];saved.logs.filter(l=>fixed.has(l.id)).forEach(l=>assert.deepEqual(l.position,fixed.get(l.id)));
const beforeBadPosition=JSON.stringify(saved);
assert.throws(()=>create(base+'/log-positions',{positions:{[inserted]:{x:'bad',y:2}}}),/位置无效/);
assert.equal(JSON.stringify(loadLocal().ideas[0]),beforeBadPosition);
const cam=cameraOf(),screen={x:300,y:200},world={x:(300-cam.x)/cam.zoom,y:(200-cam.y)/cam.zoom};
zoomCanvas(1.2,screen.x,screen.y);
assert.ok(Math.abs(world.x*cam.zoom+cam.x-screen.x)<1e-8);
assert.ok(Math.abs(world.y*cam.zoom+cam.y-screen.y)<1e-8);
assert.equal(JSON.parse(localStorage.getItem('idea-ops-camera-'+state.selected)).zoom,cam.zoom);
assert.ok(!graphSvg([{id:'safe',kind:'step',text:'<script>alert(1)</script>',parents:[],at:new Date().toISOString()}],null).includes('<script>'));
console.log('PASS: graph mutations, fixed positions across deletion/reload/addition, negative and large coordinates, invalid-position rollback, cursor-anchored zoom, saved viewport');
`,context);
assert.ok(!html.includes('capture-form'));
assert.ok(!html.includes('commit-form'));
vm.runInContext(`(async()=>{
  await refresh();
  const before=loadLocal().ideas[0];
  const source=before.logs.find(l=>l.id===inserted);
  const target=before.logs.find(l=>l.id===join);
  const coordinates=before.logs.map(l=>[l.id,l.position]);
  linking=source.id;await selectNode(target.id);
  const after=loadLocal().ideas[0];
  assert.equal(after.logs.length,before.logs.length);
  assert.ok(after.logs.find(l=>l.id===target.id).after.includes(source.id));
  assert.deepEqual(after.logs.map(l=>[l.id,l.position]),coordinates);
  linking=source.id;await selectNode(target.id);
  assert.equal(loadLocal().ideas[0].logs.find(l=>l.id===target.id).after.filter(id=>id===source.id).length,1);
  linking=target.id;await selectNode(source.id);
  assert.ok(!loadLocal().ideas[0].logs.find(l=>l.id===source.id).after.includes(target.id));
  assert.equal(linking,target.id);
  closeTools();assert.equal(linking,null);
  assert.ok(graphSvg(graphNodes(after),null).includes('data-action="connect"'));
  const original=loadLocal().ideas[0].logs.find(l=>l.id===target.id);
  create(base+'/log-update',{log:target.id,kind:'progress',text:'完整内容修改\\n第二行 <标签>'});
  const edited=loadLocal().ideas[0].logs.find(l=>l.id===target.id);
  assert.equal(edited.text,'完整内容修改\\n第二行 <标签>');
  assert.equal(edited.kind,'progress');assert.equal(edited.at,original.at);
  assert.deepEqual(edited.position,original.position);assert.deepEqual(edited.after,original.after);
  assert.ok(edited.updated_at);
  assert.throws(()=>create(base+'/log-update',{log:target.id,kind:'step',text:'   '}),/填写标题/);
  assert.deepEqual(loadLocal().ideas[0].logs.find(l=>l.id===target.id),edited);
  openNodeCard(loadLocal().ideas[0],target.id);
  assert.ok(document.querySelector('#node-tools').innerHTML.includes('&lt;标签&gt;'));
  console.log('PASS: node details, edit persistence, unchanged relationships/position/time, empty validation, escaped content');
  create(base+'/log-update',{log:target.id,kind:'step',title:'简短标题',text:'仅展开卡片可见的正文'});
  const titled=loadLocal().ideas[0];
  assert.equal(commitsOf(titled).find(l=>l.id===target.id).title,'简短标题');
  const titledGraph=graphSvg(graphNodes(titled),null);
  assert.ok(titledGraph.includes('简短标题'));assert.ok(!titledGraph.includes('仅展开卡片可见的正文'));
  assert.ok(!canvasPreview(titled).includes('仅展开卡片可见的正文'));
  openNodeCard(titled,target.id);assert.ok(document.querySelector('#node-tools').innerHTML.includes('仅展开卡片可见的正文'));
  const legacy={text:'旧标题\\n旧正文'};
  assert.equal(nodeTitle(legacy),'旧标题');assert.equal(legacy.text,'旧标题\\n旧正文');
  console.log('PASS: title-only canvas and preview, details only in expanded card, legacy text preserved');
  const frozenGraph=JSON.stringify(loadLocal().ideas[0].logs);
  const workForm=(mode,values,record='')=>({dataset:{mode,idea:project.id,record},values,querySelector:()=>({disabled:false})});
  await saveWorkEditor(workForm('edit-project',{title:'工作台测试',summary:'真实项目简介',tags:'AI，效率 AI',priority:'high',project_name:'个人项目',status:'active',blocker:''}));
  let workIdea=loadLocal().ideas[0];assert.equal(workIdea.summary,'真实项目简介');assert.deepEqual(workIdea.tags,['AI','效率']);assert.equal(workIdea.priority,'high');assert.equal(workIdea.project_name,'个人项目');
  await saveWorkEditor(workForm('edit-blocker',{status:'blocked',blocker:'等待测试资源'}));
  workIdea=loadLocal().ideas[0];assert.equal(workIdea.status,'blocked');assert.ok(workIdea.blocker_updated_at);
  create(base,{next_action:'已有的下一步'});await refresh();
  await saveWorkEditor(workForm('add-task',{text:'测试行动',owner:'我',hours:'2.5',due:'2026-09-30'}));
  workIdea=loadLocal().ideas[0];assert.equal(workIdea.next_steps.length,2);assert.equal(workIdea.next_steps[0].text,'已有的下一步');
  const actionTask=workIdea.next_steps.at(-1);assert.equal(actionTask.hours,2.5);assert.equal(actionTask.due,'2026-09-30');
  await saveWorkEditor(workForm('edit-task',{text:'修改行动',owner:'负责人 A',hours:'3',due:'2026-10-01'},actionTask.id));
  const toggle={dataset:{taskToggle:actionTask.id},checked:true,disabled:false};
  await document.querySelector('#detail').handlers.change[0]({target:toggle});
  workIdea=loadLocal().ideas[0];assert.equal(workIdea.next_steps.at(-1).done,true);assert.equal(workIdea.next_steps.at(-1).owner,'负责人 A');
  assert.equal(JSON.stringify(workIdea.logs),frozenGraph);
  const beforeInvalid=JSON.stringify(workIdea);
  await saveWorkEditor(workForm('add-task',{text:'错误日期',owner:'',hours:'1',due:'2026-02-30'}));
  assert.equal(JSON.stringify(loadLocal().ideas[0]),beforeInvalid);
  await saveWorkEditor(workForm('add-record',{kind:'resistance',text:'实际遇到的新阻力'}));
  workIdea=loadLocal().ideas[0];assert.equal(workIdea.logs.at(-1).text,'实际遇到的新阻力');assert.equal(workIdea.logs.length,JSON.parse(frozenGraph).length+1);
  workIdea.logs.slice(0,-1).forEach((log,index)=>assert.deepEqual(log,JSON.parse(frozenGraph)[index]));
  const overview=overviewHtml(workIdea);for(const label of ['当前阻塞','最近记录','下一步','负责人 A','个人项目']) assert.ok(overview.includes(label));
  const preview=overviewHtml({...workIdea,logs:Array.from({length:5},(_,index)=>({id:'REC-'+index,source:'user',kind:'progress',text:'记录'+index,at:'2026-09-15T10:0'+index+':00Z',after:[]}))});
  assert.equal((preview.split('<details')[0].match(/class="record-row"/g)||[]).length,3);
  assert.equal((preview.split('<details')[1].match(/class="record-row"/g)||[]).length,2);
  assert.ok(!preview.includes('<details open'));
  assert.ok(!preview.includes('data-work="add-record"')&&!preview.includes('data-work="edit-blocker"'));
  assert.ok(preview.includes('data-work="view-record"'));
  const thumbnail=canvasPreview(workIdea);
  assert.ok(thumbnail.includes('data-work="canvas-preview"'));
  assert.equal((thumbnail.match(/<g>/g)||[]).length,workIdea.logs.length);
  const expectedEdges=workIdea.logs.reduce((sum,log)=>sum+log.after.length,0);
  assert.equal((thumbnail.match(/<path /g)||[]).length,expectedEdges);
  state.view='overview';
  await document.querySelector('#detail').handlers.click[0]({target:{closest:selector=>selector==='[data-work]'?{dataset:{work:'canvas-preview'}}:null}});
  assert.equal(state.view,'canvas');
  const fitted=cameraOf(),bounds=graphBounds(graphNodes(state.ideas.find(i=>i.id===state.selected)));
  assert.ok(bounds.minX*fitted.zoom+fitted.x>=0);
  assert.ok((bounds.minX+bounds.width)*fitted.zoom+fitted.x<=800);
  assert.ok(bounds.minY*fitted.zoom+fitted.y>=0);
  assert.ok((bounds.minY+bounds.height)*fitted.zoom+fitted.y<=700);
  console.log('PASS: full-canvas thumbnail and click-to-fit navigation');
  state.search='效率';assert.equal(visibleIdeas().length,1);state.search='不匹配搜索';assert.equal(visibleIdeas().length,0);state.search='';
  assert.throws(()=>validateProjectChanges({status:'constructor'}),/无效状态/);
  assert.throws(()=>validateProjectChanges({next_steps:[{id:'x',text:'test',done:false,hours:-1}]}),/预计用时/);
  console.log('PASS: workbench metadata, tags, priority, blockers, record creation, legacy next action, task editing/completion, deadlines, search, unchanged graph');
  console.log('PASS: connect via node selection, coordinates preserved, duplicate/cycle prevention, cancellation');
  const oldCount=loadLocal().ideas.length;
  state.page='workbench';openHomeCapture();assert.equal(state.page,'home');assert.equal(document.querySelector('#home-idea-form').hidden,false);
  const homeForm={values:{title:'首页新想法',summary:'可选简介'},querySelector:()=>({disabled:false}),reset(){this.didReset=true},hidden:false};
  await saveHomeIdea(homeForm);
  assert.equal(state.page,'home');assert.equal(homeForm.hidden,true);assert.ok(homeForm.didReset);
  assert.equal(loadLocal().ideas.length,oldCount+1);
  const homeCreated=loadLocal().ideas.find(idea=>idea.title==='首页新想法');
  assert.equal(homeCreated.summary,'可选简介');assert.equal(homeCreated.status,'inbox');assert.deepEqual(homeCreated.logs,[]);
  await saveHomeIdea({...homeForm,values:{title:'   '}});assert.equal(loadLocal().ideas.length,oldCount+1);
  console.log('PASS: home inline capture, title/summary persistence, no canvas navigation, empty-name validation');
})()`,context).catch(error=>{console.error(error);process.exitCode=1;});
