const assert = require('node:assert/strict');
const {mergeOfflineIdeas: merge} = require('../assets/offline-bridge.js');
const clone = value => JSON.parse(JSON.stringify(value));
const idea = {id:'A',title:'制作过程',summary:'初版',logs:[{id:'L',text:'起点',after:[]}],relations:[]};
const packet = {workspace:'workspace-A',data:{version:1,ideas:[idea]}};
const local = {version:1,ideas:[{id:'existing',title:'网页旧记录',logs:[],relations:[]}]};
let first = merge(local,packet);
assert.equal(first.added,1);
assert.equal(first.data.ideas.length,2);
assert.equal(local.ideas.length,1);
assert.deepEqual(merge(first.data,packet).data,first.data);
let moved = clone(first.data);
moved.ideas[1].logs[0].position={x:420,y:80};
let next = clone(packet); next.data.ideas[0].summary='Codex补充目标';
let updated = merge(moved,next);
assert.equal(updated.updated,1);
assert.deepEqual(updated.data.ideas[1].logs[0].position,{x:420,y:80});
let edited=clone(moved); edited.ideas[1].logs[0].text='用户编辑';
let conflict=merge(edited,next);
assert.deepEqual(conflict.conflicts,['制作过程']);
assert.equal(conflict.data.ideas[1].logs[0].text,'用户编辑');
assert.deepEqual(merge(edited,packet).data,edited);
let deleted=clone(first.data); deleted.ideas.pop();
assert.equal(merge(deleted,packet).data.ideas.length,1);
assert.equal(merge(deleted,next).conflicts.length,1);
let collision=clone(packet);collision.workspace='workspace-B';collision.data.ideas[0].title='同ID不同想法';
assert.equal(merge(first.data,collision).conflicts.length,1);
assert.throws(()=>merge(local,{workspace:'bad',data:{version:1,ideas:[idea,idea]}}));
assert.deepEqual(merge(first.data,{workspace:'workspace-A',data:{version:1,ideas:[]}}).data,first.data);
console.log('PASS: first import, repeat, existing data, updates, positions, edits/conflicts, deletion, ID collision, invalid data, remote omission');
